const express = require('express');
const { getAllUsers, getUserById, getAllContacts, deleteUser, deleteContact, updateUser, getContactById, updateContact } = require('../controllers/admin-controller');
const authMiddleware = require('../middlewares/auth-middleware');
const adminMiddleware = require('../middlewares/admin-middleware');
const router = express.Router();
router.route("/users").get(authMiddleware, adminMiddleware, getAllUsers);
router.route("/user/:id/edit").get(authMiddleware, adminMiddleware, getUserById);
router.route("/user/:id/update").patch(authMiddleware, adminMiddleware, updateUser);
router.route("/user/:id/delete").delete(authMiddleware, adminMiddleware, deleteUser);
router.route("/contacts").get(authMiddleware, getAllContacts);
router.route("/contact/:id/edit").get(authMiddleware, adminMiddleware, getContactById);
router.route("/contact/:id/update").patch(authMiddleware, adminMiddleware, updateContact);
router.route("/contact/:id/delete").delete(authMiddleware, adminMiddleware, deleteContact);
module.exports = router;
